#!/usr/bin/env python3
"""Download Latin Google Fonts for self-hosting and emit css/fonts.css."""
import re
import urllib.request
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "assets" / "fonts"
CSS_OUT = ROOT / "css" / "fonts.css"

FAMILIES = "Cormorant+Garamond:400,400i,500,600,700|Inter:400,500,600"
CSS_URL = f"https://fonts.googleapis.com/css?family={FAMILIES}&subset=latin&display=swap"

UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

OUT_DIR.mkdir(parents=True, exist_ok=True)

req = urllib.request.Request(CSS_URL, headers={"User-Agent": UA})
with urllib.request.urlopen(req, timeout=30) as r:
    css = r.read().decode("utf-8")

# Extract each comment + @font-face block
blocks = re.findall(r"/\*\s*([^*]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css, re.DOTALL)
new_blocks = []

for subset, block in blocks:
    subset = subset.strip().lower()
    if subset != "latin":
        continue

    url_match = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)\s+format\('woff2'\)", block)
    if not url_match:
        continue

    remote_url = url_match.group(1)
    filename = urllib.parse.urlparse(remote_url).path.split("/")[-1]
    local_path = OUT_DIR / filename

    if not local_path.exists():
        print(f"Downloading {filename}")
        f_req = urllib.request.Request(remote_url, headers={"User-Agent": UA})
        with urllib.request.urlopen(f_req, timeout=60) as fr, open(local_path, "wb") as fw:
            fw.write(fr.read())
    else:
        print(f"Exists {filename}")

    local_block = re.sub(
        r"src:\s*url\([^)]+\)\s+format\('woff2'\)",
        f"src: url('../assets/fonts/{filename}') format('woff2')",
        block,
    )
    new_blocks.append(local_block.strip())

CSS_OUT.write_text(
    "/* Self-hosted Latin fonts (OFL-licensed). Generated by scripts/download-fonts.py */\n\n"
    + "\n\n".join(new_blocks)
    + "\n",
    encoding="utf-8",
)

print(f"Wrote {CSS_OUT}")
print(f"Total latin font files: {len(new_blocks)}")
